services:
  nextlogindb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    container_name: login-nextjs
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db